quarkus:
  swagger-ui:
    always-include: true
    path: /swagger
  datasource:
      reactive:
        url: mysql:///booking
      db-kind: mysql
  log:
    level: INFO
lock:
  server-list: redis://localhost:26739
  redis-embedded:
    start-server: true
  master: master1
