quarkus:
  swagger-ui:
    always-include: true
    path: /swagger
  datasource:
      reactive:
        url: mysql:///booking
      db-kind: mysql
  log:
    level: INFO
  native:
    additional-build-args: "--allow-incomplete-classpath,--enable-all-security-services,-H:EnableURLProtocols=http\\,https"
lock:
  server-list: redis://localhost:26739
  redis-embedded:
    start-server: true
  master: master1
